# For our root CA, we can use a self-signed ClusterIssuer. This will create a
# self-signed certificate that cert-manager will use for its root CA.

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-self-signed-issuer
spec:
  # This ClusterIssuer uses a self-signed certificate.
  selfSigned: {}
