apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-vault-issuer
spec:
  vault:
    path: pki/root/sign-intermediate
    server: http://vault.vault.svc.cluster.local:8200
    auth:
      tokenSecretRef:
          name: vault-token
          key: token
