---
# Recalling that our certificates all exist in the cert-manager namespace,
# we'll use trust-manager to copy the public key of our trust anchor
# certificate from the cert-manager namespace to the linkerd namespace, so
# that Linkerd can actually use it to validate certificates.
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
spec:
  sources:
  - secret:
      name: "linkerd-identity-trust-roots"
      key: "tls.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
