kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# Three nodes
nodes:
- role: control-plane
  # Connect ports 80 and 443 from the host
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "127.0.0.1"
  - containerPort: 443
    hostPort: 443
    # optional: set the bind address on the host
    # 0.0.0.0 is the current default
    listenAddress: "127.0.0.1"
- role: worker
- role: worker

