namespace: podinfo
bases:
  - "github.com/stefanprodan/podinfo/kustomize/?ref=6.4.1"

resources:
  - ns.yaml
  - canary.yaml
  - generator.yaml
  - frontend.yaml

patchesStrategicMerge:
  - patch.yaml