#!/bin/sh

# This was generated by hand, by installing a bunch of stuff,
# figuring out what images it used, and assembling them here.
# A better way would be to pull images through the local Docker
# cache. I haven't gotten K3d to do that yet.

docker pull cr.l5d.io/linkerd/controller:stable-2.12.2
docker pull cr.l5d.io/linkerd/metrics-api:stable-2.12.2
docker pull cr.l5d.io/linkerd/policy-controller:stable-2.12.2
docker pull cr.l5d.io/linkerd/proxy-init:v2.0.0
docker pull cr.l5d.io/linkerd/proxy:stable-2.12.2
docker pull cr.l5d.io/linkerd/tap:stable-2.12.2
docker pull cr.l5d.io/linkerd/web:stable-2.12.1
docker pull cr.l5d.io/linkerd/web:stable-2.12.2
docker pull docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
docker pull docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
docker pull docker.l5d.io/buoyantio/emojivoto-web:v11
docker pull prom/prometheus:v2.30.3
docker pull quay.io/jetstack/cert-manager-cainjector:v1.10.0
docker pull quay.io/jetstack/cert-manager-controller:v1.10.0
docker pull quay.io/jetstack/cert-manager-ctl:v1.10.0
docker pull quay.io/jetstack/cert-manager-trust:v0.2.0
docker pull quay.io/jetstack/cert-manager-webhook:v1.10.0

docker save \
    cr.l5d.io/linkerd/controller:stable-2.12.2 \
    cr.l5d.io/linkerd/metrics-api:stable-2.12.2 \
    cr.l5d.io/linkerd/policy-controller:stable-2.12.2 \
    cr.l5d.io/linkerd/proxy-init:v2.0.0 \
    cr.l5d.io/linkerd/proxy:stable-2.12.2 \
    cr.l5d.io/linkerd/tap:stable-2.12.2 \
    cr.l5d.io/linkerd/web:stable-2.12.1 \
    cr.l5d.io/linkerd/web:stable-2.12.2 \
    docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11 \
    docker.l5d.io/buoyantio/emojivoto-voting-svc:v11 \
    docker.l5d.io/buoyantio/emojivoto-web:v11 \
    prom/prometheus:v2.30.3 \
    quay.io/jetstack/cert-manager-cainjector:v1.10.0 \
    quay.io/jetstack/cert-manager-controller:v1.10.0 \
    quay.io/jetstack/cert-manager-ctl:v1.10.0 \
    quay.io/jetstack/cert-manager-trust:v0.2.0 \
    quay.io/jetstack/cert-manager-webhook:v1.10.0 \
    > images.tar
